### PR TITLE
[incubator-kie-issues-1485] Reenable event test in ProcessTestEvents in kogito-apps

### PR DESCRIPTION
**Pull request by elguardian**
Closes: https://github.com/apache/incubator-kie-issues/issues/1485

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/display/redirect

**Test results:**
- PASSED: 3362
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi3_0NoAuth/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0NoAuth</a></summary>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.quarkus.it.openapi.client.mocks.AuthSecurityMockService
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.kie.kogito.integrationtests.quarkus/TaskIT/testUpdateTaskInfo/">org.kie.kogito.integrationtests.quarkus.TaskIT.testUpdateTaskInfo</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/2/testReport/org.kie.kogito.integrationtests.springboot/TaskTest/testUpdateTaskInfo/">org.kie.kogito.integrationtests.springboot.TaskTest.testUpdateTaskInfo</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/display/redirect

**Test results:**
- PASSED: 3376
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/testReport/org.kie.kogito.integrationtests.quarkus/TaskIT/testUpdateTaskInfo/">org.kie.kogito.integrationtests.quarkus.TaskIT.testUpdateTaskInfo</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/3/testReport/org.kie.kogito.integrationtests.springboot/TaskTest/testUpdateTaskInfo/">org.kie.kogito.integrationtests.springboot.TaskTest.testUpdateTaskInfo</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/4/display/redirect

**Test results:**
- PASSED: 3378
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/4/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/4/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/4/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/5/display/redirect

**Test results:**
- PASSED: 2664
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/5/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/5/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/5/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/6/display/redirect

**Test results:**
- PASSED: 2155
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/6/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/6/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/6/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3722 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/7/display/redirect

**Test results:**
- PASSED: 3380
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3722/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Review by martinweiler — APPROVED** [review]
LGTM @elguardian

**Review by pefernan — APPROVED** [review]

**Pull request merged**
