### PR TITLE
[kie-issues-249] Data index improvements

### PR DESCRIPTION
**Pull request by elguardian**
Issue: https://github.com/apache/incubator-kie-issues/issues/249

depends on https://github.com/apache/incubator-kie-drools/pull/5529

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/4/display/redirect

**Test results:**
- PASSED: 3384
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/4/testReport/org.kie.kogito.serverless.workflow.executor/StaticFluentWorkflowApplicationTest/testSwitchLoop/">org.kie.kogito.serverless.workflow.executor.StaticFluentWorkflowApplicationTest.testSwitchLoop</a></summary>
Process f6c8f278-11d9-49e0-b874-484f7e623c98 has not finished after PT2.5S
</details>

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/8/display/redirect

**Test results:**
- PASSED: 3380
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/8/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcess/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcess</a></summary>
<br/>Expecting actual:<br/>  ProcessInstanceNodeDataEvent {specVersion=1.0, id='f34bdc18-d220-4dcd-8228-bab5561b6ed2', source=http://myhost/UserTasksProcess, type='ProcessInstanceNodeDataEvent', time=2023-10-05T13:19:20.632851Z, subject='null', dataContentType='application/json', dataSchema=null, data=ProcessInstanceNodeEventBody [eventDate=Thu Oct 05 13:19:20 UTC 2023, eventUser=null, eventType=1, processId=UserTasksProcess, processVersion=1.0, processInstanceId=2969d592-fa49-4489-bf19-c39e44382f94, connectionNodeInstanceId=null, nodeDefinitionId=EndEvent_1, nodeName=End Event 1, nodeType=EndNode, nodeInstanceId=c5f864fa-6529-4164-b84e-4551beb11b51, data={}], kogitoProcessInstanceId='2969d592-fa49-4489-bf19-c39e44382f94', kogitoRootProcessInstanceId='null', kogitoProcessId='UserTasksProcess', kogitoRootProcessId='null', kogitoAddons='test', kogitoIdentity='null', extensionAttributes={kogitoproctype=BPMN, kogitoprocinstanceid=2969d592-fa49-4489-bf19-c39e44382f94, kogitoprocist=1, kogitoprocversion=1.0, kogitoprocid=UserTasksProcess, kogitoaddons=test}}<br/>to be an instance of:<br/>  org.kie.kogito.event.process.ProcessInstanceStateDataEvent<br/>but was instance of:<br/>  org.kie.kogito.event.process.ProcessInstanceNodeDataEvent
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/8/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expected size: 1 but was: 3 in:<br/>{"number"=6, "numberType"="even", "perfect"=false}
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/8/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testTypesPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testTypesPojo</a></summary>
<br/>Expected size: 9 but was: 3 in:<br/>{"message"="my name is javierito and in my native language dog is translated to perro and the header pepe is pepa", "result"=4, "user"="anonymous"}
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/8/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testFilterPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testFilterPojo</a></summary>
<br/>Expected size: 1 but was: 3 in:<br/>{"divisor"=2, "input"=[2, 4, 6, 8, 10], "output"=[2, 3, 4, 5, 6]}
</details>

**Comment by kie-ci3** [comment]
**PR job** `#9` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/9/display/redirect

**Test results:**
- PASSED: 3383
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/9/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expected size: 1 but was: 3 in:<br/>{"number"=6, "numberType"="even", "perfect"=false}
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/9/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testTypesPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testTypesPojo</a></summary>
<br/>Expected size: 9 but was: 3 in:<br/>{"message"="my name is javierito and in my native language dog is translated to perro and the header pepe is pepa", "result"=4, "user"="anonymous"}
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/9/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testFilterPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testFilterPojo</a></summary>
<br/>Expected size: 1 but was: 3 in:<br/>{"divisor"=2, "input"=[2, 4, 6, 8, 10], "output"=[2, 3, 4, 5, 6]}
</details>

**Comment by kie-ci3** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/10/display/redirect

**Test results:**
- PASSED: 3385
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/10/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/11/display/redirect

**Test results:**
- PASSED: 3311
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/11/testReport/org.kie.kogito.quarkus.workflows/AsyncAPIIT/testConsumer/">org.kie.kogito.quarkus.workflows.AsyncAPIIT.testConsumer</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor#launchDatabases threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:345)<br/> at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.launchDatabases(DevServicesDatasourceProcessor.java:136)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:829)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.postgresql.deployment.PostgresqlDevServicesProcessor$1.startDatabase(PostgresqlDevServicesProcessor.java:65)<br/> at io.quarkus.datasource.deployment.devservices.DevServicesDatasourceProcessor.startDevDb(DevServicesDatasourceProcessor.java:282)<br/> ... 12 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)<br/> at org.testcontainers.utility.RyukResourceReaper.register(RyukResourceReaper.java:68)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:423)<br/> ... 18 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 22 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 23 more<br/>Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.4"}<br/><br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:427)<br/> ... 25 more<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/2/display/redirect

**Test results:**
- PASSED: 3372
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/2/testReport/org.kie.kogito.events.mongodb/MongoDBEventPublisherTest/configure/">org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure</a></summary>
<br/>Argument(s) are different! Wanted:<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceStateDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure(MongoDBEventPublisherTest.java:129)<br/>Actual invocations have different arguments:<br/>mongoDatabase.withCodecRegistry(<br/>    ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@22014338]}, ProvidersCodecRegistry{codecProviders=[org.kie.kogito.events.mongodb.codec.EventMongoDBCodecProvider@22ecee76, org.bson.codecs.pojo.PojoCodecProvider@905e189]}]}<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:69)<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:70)<br/>mongoDatabase.getCollection(<br/>    "testTECollection",<br/>    class org.kie.kogito.event.usertask.UserTaskInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:71)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/2/testReport/org.kie.kogito.tracing/QuarkusTracingAddonDevServicesIT/testEvaluateLoanEligibility/">org.kie.kogito.tracing.QuarkusTracingAddonDevServicesIT.testEvaluateLoanEligibility</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/2/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#13` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/display/redirect

**Test results:**
- PASSED: 3370
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/testReport/org.kie.kogito.events.mongodb/MongoDBEventPublisherTest/configure/">org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure</a></summary>
<br/>Argument(s) are different! Wanted:<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceStateDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure(MongoDBEventPublisherTest.java:129)<br/>Actual invocations have different arguments:<br/>mongoDatabase.withCodecRegistry(<br/>    ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@22014338]}, ProvidersCodecRegistry{codecProviders=[org.kie.kogito.events.mongodb.codec.EventMongoDBCodecProvider@22ecee76, org.bson.codecs.pojo.PojoCodecProvider@905e189]}]}<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:69)<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:70)<br/>mongoDatabase.getCollection(<br/>    "testTECollection",<br/>    class org.kie.kogito.event.usertask.UserTaskInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:71)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/testReport/org.kie.kogito.process.definitions/ProcessDefinitionsResourceTest/testAddDefinition/">org.kie.kogito.process.definitions.ProcessDefinitionsResourceTest.testAddDefinition</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/testReport/org.kie.kogito.quarkus.serverless.workflow.deployment.livereload/LiveReloadProcessorTest/testGrpc/">org.kie.kogito.quarkus.serverless.workflow.deployment.livereload.LiveReloadProcessorTest.testGrpc</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/testReport/org.kie.kogito.quarkus.serverless.workflow.deployment.livereload/LiveReloadProcessorTest/testAsyncApi/">org.kie.kogito.quarkus.serverless.workflow.deployment.livereload.LiveReloadProcessorTest.testAsyncApi</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/13/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#15` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3241 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/15/display/redirect

**Test results:**
- PASSED: 3373
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/15/testReport/org.kie.kogito.events.mongodb/MongoDBEventPublisherTest/configure/">org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure</a></summary>
<br/>Argument(s) are different! Wanted:<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceStateDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisherTest.configure(MongoDBEventPublisherTest.java:129)<br/>Actual invocations have different arguments:<br/>mongoDatabase.withCodecRegistry(<br/>    ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@42775280]}, ProvidersCodecRegistry{codecProviders=[org.kie.kogito.events.mongodb.codec.EventMongoDBCodecProvider@1cce2194, org.bson.codecs.pojo.PojoCodecProvider@51645204]}]}<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:69)<br/>mongoDatabase.getCollection(<br/>    "testPICollection",<br/>    class org.kie.kogito.event.process.ProcessInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:70)<br/>mongoDatabase.getCollection(<br/>    "testTECollection",<br/>    class org.kie.kogito.event.usertask.UserTaskInstanceDataEvent<br/>);<br/>-> at org.kie.kogito.events.mongodb.MongoDBEventPublisher.configure(MongoDBEventPublisher.java:71)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3241/15/testReport/org.kie.kogito.quarkus.workflows/PojoServiceIT/testPojo/">org.kie.kogito.quarkus.workflows.PojoServiceIT.testPojo</a></summary>
<br/>Expecting value to be true but was false
</details>

**Review by pefernan — APPROVED** [review]

**Review by martinweiler — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Pull request merged**
