### PR TITLE
[incubator-kie-issues-1555] Multiple sub process instances cancelled by the same timer.

### PR DESCRIPTION
**Pull request by elguardian**
Closes: https://github.com/apache/incubator-kie-issues/issues/1555

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3745 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3745/1/display/redirect

**Test results:**
- PASSED: 3396
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3745/1/testReport/org.kie.kogito.quarkus.workflows/CompensationRestIT/testErrorRest2/">org.kie.kogito.quarkus.workflows.CompensationRestIT.testErrorRest2</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Review by martinweiler — CHANGES_REQUESTED** [review]
@elguardian great work!

Some feedback:
* The sample application (run in the compact arch example) finishes successfully with the latest changes
* The newly added test `testMultiInstanceLoopSubprocessBoundaryTimer` works even without the fixes
* I see the same test failure as in CI - `IntermediateEventTest.testIntermediateCatchEventSignalAndBoundarySignalEvent:1777`

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3745 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3745/6/display/redirect

**Test results:**
- PASSED: 3462
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3745/6/testReport/org.kie.kogito.quarkus.workflows/CompensationRestIT/testErrorRest2/">org.kie.kogito.quarkus.workflows.CompensationRestIT.testErrorRest2</a></summary>
1 expectation failed.<br/>JSON path workflowdata.isEven doesn't match.<br/>Expected: is <false><br/>  Actual: null<br/>
</details>

**Review by martinweiler — APPROVED** [review]
Great work @elguardian

**Review by porcelli — APPROVED** [review]

**Pull request merged**
