### PR TITLE
Bump openapi generator version

### LINKED ISSUE #3378: Bump openapi generator version
## Describe the bug
When using json specs to send request to an endpoint, if the specs has arrays but none is provided, a null value for that field is included in the request which may cause issue if the service receiving the request handle it badly.

Fixed by latest openapi generator version (https://github.com/quarkiverse/quarkus-openapi-generator/pull/634) 

## Expected behavior
No response

## Actual behavior
No response

## How to Reproduce?
No response

## Output of uname -a or ver
No response

## Output of java -version
No response

## GraalVM version (if different from Java)
No response

## Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)
No response

## Build tool (ie. output of mvnw --version or gradlew --version)
No response

## Additional information
No response

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by gabriel-farache**
Closes #3378

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]

**Comment by fjtirado** [comment]
@gabriel-farache looks like there is a regresion with the new version of OpenAPI. Investigating it

**Comment by fjtirado** [comment]
@hbelmiro There is a regresion in one of the test, which Im afraid is caused by this change https://github.com/quarkiverse/quarkus-openapi-generator/commit/ed66066f8ab35938253c7a83a94a7adbf5d1b042
The test was expecting those three values for X-Client-Id `Bearer mytoken,Bearer mytoken,Bearer` but now it is getting `Bearer mytoken,Bearer mytoken`

**Comment by fjtirado** [comment]
@ after taking a look at the test, I think we can safely remove the latest Bearer from the expected X-cllient-id, but I would like to have a second opinion

**Review by ricardozanini — APPROVED** [review]

**Comment by hbelmiro** [comment]
@fjtirado I think you can remove it.

**Review by hbelmiro — APPROVED** [review]

**Review by fjtirado — COMMENTED** [review]
@gabriel-farache Can you modify the failing test as indicated in one of my comments?. 
It is just a removal of a string in the expected results. Thanks

**Comment by gabriel-farache** [comment]
> @gabriel-farache Can you modify the failing test as indicated in one of my comments?.
It is just a removal of a string in the expected results. Thanks
@fjtirado Done, I removed the last `,Bearer` in the expected string

**Pull request merged**
