### PR TITLE
[incubator-kie-issues-1286] Adhoc functionality missing in kogito jBPM engine

### PR DESCRIPTION
**Pull request by elguardian**
Closes: https://github.com/apache/incubator-kie-issues/issues/1286

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3543 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/display/redirect

**Test results:**
- PASSED: 3233
- FAILED: 30

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/ErrorEventTest/testErrorBoundaryEventOnServiceTask/">org.jbpm.bpmn2.ErrorEventTest.testErrorBoundaryEventOnServiceTask</a></summary>
Node(s) not executed: end0
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/ErrorEventTest/testSignallingExceptionServiceTask/">org.jbpm.bpmn2.ErrorEventTest.testSignallingExceptionServiceTask</a></summary>
Process instance is not active.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/ErrorEventTest/testCatchErrorBoundaryEventOnTask/">org.jbpm.bpmn2.ErrorEventTest.testCatchErrorBoundaryEventOnTask</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/FlowTest/testInclusiveSplitAndJoinWithEnd/">org.jbpm.bpmn2.FlowTest.testInclusiveSplitAndJoinWithEnd</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/FlowTest/testInclusiveJoinWithLoopAndHumanTasks/">org.jbpm.bpmn2.FlowTest.testInclusiveJoinWithLoopAndHumanTasks</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/FlowTest/testInclusiveSplitAndJoinWithTimer/">org.jbpm.bpmn2.FlowTest.testInclusiveSplitAndJoinWithTimer</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventCycleISO/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventCycleISO</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessMessage/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessMessage</a></summary>
Node(s) not executed: end
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testSignalBoundaryEventNoInteruptOnMultiInstanceSubprocess/">org.jbpm.bpmn2.IntermediateEventTest.testSignalBoundaryEventNoInteruptOnMultiInstanceSubprocess</a></summary>
<br/>Expecting actual not to be null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycleWithErrorWithPersistence/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycleWithErrorWithPersistence</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventCycle2/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventCycle2</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessSignal/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessSignal</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessSignalWithStateNode/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessSignalWithStateNode</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessWithEmbeddedSignals/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessWithEmbeddedSignals</a></summary>
<br/>Expecting actual not to be null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessConditional/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessConditional</a></summary>
Node(s) not executed: end
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycle2/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycle2</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycleWithError/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycleWithError</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testSignallingExceptionServiceTask/">org.jbpm.bpmn2.IntermediateEventTest.testSignallingExceptionServiceTask</a></summary>
Process instance is not active.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycleISO/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycleISO</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessTimer/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessTimer</a></summary>
<br/>Expected size: 1 but was: 0 in:<br/>[]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/ProcessFactoryTest/testBoundaryTimerTimeCycle/">org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeCycle</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/ProcessFactoryTest/testBoundaryTimerTimeDuration/">org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeDuration</a></summary>
[Process instance is not active.] <br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.jbpm.bpmn2/StandaloneBPMNProcessTest/testSignallingExceptionServiceTask/">org.jbpm.bpmn2.StandaloneBPMNProcessTest.testSignallingExceptionServiceTask</a></summary>
Process instance is not active.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.tests/EventSubProcessIT/testEventSignalSubProcessWithData/">org.kie.kogito.codegen.tests.EventSubProcessIT.testEventSignalSubProcessWithData</a></summary>
<br/>expected: 1<br/> but was: 2
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.tests/TimerEventIT/testIntermediateCycleTimerEvent/">org.kie.kogito.codegen.tests.TimerEventIT.testIntermediateCycleTimerEvent</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/maven.invoker.it/integration-tests-kogito-plugin-it/integration_tests_kogito_plugin_it/">maven.invoker.it.integration-tests-kogito-plugin-it.integration-tests-kogito-plugin-it</a></summary>
The build exited with code 1. See /home/jenkins/jenkins-agent/workspace/_jobs_kogito-runtimes-pr_PR-3543/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/quarkus/integration-tests/integration-tests-kogito-plugin/target/it/integration-tests-kogito-plugin-it/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.acme.travels/SignalProcessTest/testProcessSignals/">org.acme.travels.SignalProcessTest.testProcessSignals</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.integrationtests.quarkus/SignalProcessIT/testProcessSignals/">org.kie.kogito.integrationtests.quarkus.SignalProcessIT.testProcessSignals</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/maven.invoker.it/integration-tests-springboot-processes-it/integration_tests_springboot_processes_it/">maven.invoker.it.integration-tests-springboot-processes-it.integration-tests-springboot-processes-it</a></summary>
The build exited with code 1. See /home/jenkins/jenkins-agent/workspace/_jobs_kogito-runtimes-pr_PR-3543/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/springboot/integration-tests/target/it/integration-tests-springboot-processes-it/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.integrationtests.springboot/SignalProcessTest/testProcessSignals/">org.kie.kogito.integrationtests.springboot.SignalProcessTest.testProcessSignals</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3543 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/display/redirect

**Test results:**
- PASSED: 2116
- FAILED: 12

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenStartFrom/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenStartFrom</a></summary>
Node with id my_node_id not found within process instance null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenTrigger/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenTrigger</a></summary>
Node with id my_node_id not found within process instance null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[50]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[50]</a></summary>
Error while elaborating process id = "CaseWithTwoStages", packageName = "org.drools.bpmn2": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[53]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[53]</a></summary>
Error while elaborating process id = "CaseWithTwoStagesConditions", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[64]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[64]</a></summary>
Error while elaborating process id = "EmptyCaseStage", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[70]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[70]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataString", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[72]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[72]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataInteger", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[74]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[74]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataBoolean", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[76]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[76]</a></summary>
Error while elaborating process id = "NoStartNodeAdhocCaseWithActivationCondition", packageName = "cases": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[77]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[77]</a></summary>
Error while elaborating process id = "NoStartNodeAdhocCaseWithActivationConditionNoTerminate", packageName = "cases": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[93]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[93]</a></summary>
Error while elaborating process id = "NoStartNodeCaseWithBoundaryTimerStage", packageName = "com.myspace.case_test": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/apache_migration/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.process.impl/AdHocSubProcessIT/testActivationAdHoc/">org.kie.kogito.process.impl.AdHocSubProcessIT.testActivationAdHoc</a></summary>
ProcessInstance [c6c072a7-5861-4f57-bfb1-932bd1e41a0e] Status - Expected: 1 - Got: 2
</details>

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3543 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/display/redirect

**Test results:**
- PASSED: 3251
- FAILED: 13

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenStartFrom/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenStartFrom</a></summary>
Node with id my_node_id not found within process instance null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenTrigger/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenTrigger</a></summary>
Node with id my_node_id not found within process instance null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[6]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[6]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataBoolean", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[8]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[8]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataString", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[10]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[10]</a></summary>
Error while elaborating process id = "StageWithTaskCaseDataInteger", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[11]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[11]</a></summary>
Error while elaborating process id = "NoStartNodeAdhocCaseWithActivationConditionNoTerminate", packageName = "cases": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[12]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[12]</a></summary>
Error while elaborating process id = "NoStartNodeAdhocCaseWithActivationCondition", packageName = "cases": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[31]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[31]</a></summary>
Error while elaborating process id = "CaseWithTwoStages", packageName = "org.drools.bpmn2": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[36]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[36]</a></summary>
Error while elaborating process id = "NoStartNodeCaseWithBoundaryTimerStage", packageName = "com.myspace.case_test": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[42]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[42]</a></summary>
Error while elaborating process id = "CaseWithTwoStagesConditions", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[46]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[46]</a></summary>
Error while elaborating process id = "EmptyCaseStage", packageName = "org.jbpm": No dialect found http://www.jboss.org/drools/rule for return expression evaluator building return value expression
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.process.impl/AdHocSubProcessIT/testActivationAdHoc/">org.kie.kogito.process.impl.AdHocSubProcessIT.testActivationAdHoc</a></summary>
ProcessInstance [b895dded-7cf4-48fa-aa94-588d73dcd682] Status - Expected: 1 - Got: 2
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/1/testReport/org.kie.kogito.quarkus.workflows/CorrelationIT/correlationEventStartFromNodeTest/">org.kie.kogito.quarkus.workflows.CorrelationIT.correlationEventStartFromNodeTest</a></summary>
Condition with org.kie.kogito.quarkus.workflows.CorrelationIT was not fulfilled within 2 minutes.
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3543 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/display/redirect

**Test results:**
- PASSED: 3262
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenStartFrom/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenStartFrom</a></summary>
Node with id my_node_id not found within process instance null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3543/3/testReport/org.kie.kogito.process.impl/AbstractProcessInstanceTest/shouldTriggerNodeWhenTrigger/">org.kie.kogito.process.impl.AbstractProcessInstanceTest.shouldTriggerNodeWhenTrigger</a></summary>
Node with id my_node_id not found within process instance null
</details>

**Review by martinweiler — APPROVED** [review]
Great work @elguardian

**Review by pefernan — APPROVED** [review]
@elguardian +1 to merge.
I'd like to mention that after testing it along with consoles I found that if I try to work with Human Tasks declared inside the `AdhocSubProcess` , the DataIndex isn't getting any Human Task  related event (for example task `UserTaskStateEvent` after completing a task). I debugged a bit and looks like the `HumanTaskWorkItemDecoratorImpl` cannot obtain the `KogitoProcessEventSupport`  because the `KieRuntime` inside the Node's ProcessInstance is null, very likely an initialization error somewhere.

**Pull request merged**
