### PR TITLE
[Fix_#1632] Update postgres to 15.9 version

### PR DESCRIPTION
**Pull request by gmunozfe**
Many thanks for submitting your Pull Request :heart:! 

Closes/Fixes/Resolves [kie-issues#1632](https://github.com/apache/incubator-kie-issues/issues/1632)

Update postgres to 15.9 version

### CODE REVIEW

**Review by domhanak — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3791 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/display/redirect

**Test results:**
- PASSED: 3454
- FAILED: 27

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testMigrateSingle/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testMigrateSingle</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testMigrateAll/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testMigrateAll</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testBasicFlow/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testBasicFlow</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testMultipleProcesses/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testMultipleProcesses</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testProcessWithDifferentVersion/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testProcessWithDifferentVersion</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testRemove/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testRemove</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesIT/testUpdate/">org.kie.persistence.postgresql.PostgresqlProcessInstancesIT.testUpdate</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testMigrateSingle/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testMigrateSingle</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testMigrateAll/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testMigrateAll</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testBasicFlow/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testBasicFlow</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testMultipleProcesses/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testMultipleProcesses</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testProcessWithDifferentVersion/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testProcessWithDifferentVersion</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testRemove/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testRemove</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.persistence.postgresql/PostgresqlProcessInstancesWithLockIT/testUpdate/">org.kie.persistence.postgresql.PostgresqlProcessInstancesWithLockIT.testUpdate</a></summary>
Error finding all process instances, for processId BPMN2_UserTask
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testMultipleEmbeddedInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testMultipleEmbeddedInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testAdHocProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testAdHocProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testEmbeddedProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testEmbeddedProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testAsyncWIH/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testAsyncWIH</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testMultipleInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testMultipleInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testParallelPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testParallelPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testMultipleEmbeddedInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testMultipleEmbeddedInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testAdHocProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testAdHocProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testEmbeddedProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testEmbeddedProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testAsyncWIH/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testAsyncWIH</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/1/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testMultipleInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testMultipleInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Comment by pefernan** [comment]
hi @gmunozfe, I'm ok with the version upgrade, but which is the goal of this upgrade. The issue isn't clear to me.

Not trying to bomb th PR, it's just about understanding the change.

**Comment by gmunozfe** [comment]
> hi @gmunozfe, I'm ok with the version upgrade, but which is the goal of this upgrade. The issue isn't clear to me.
> 
> Not trying to bomb th PR, it's just about understanding the change.

Trying to upgrade postgresql to one of the latest stable releases as a good practice, in order to take advantages of enhancements, security improvements, etc. This would also help developers to stay current and make use of the latest developments in the ecosystem.

**Comment by pefernan** [comment]
@gmunozfe agree. I just wanted to know if there was another reason that was requiring the change.

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3791 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/display/redirect

**Test results:**
- PASSED: 3468
- FAILED: 13

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testMultipleEmbeddedInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testMultipleEmbeddedInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testAdHocProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testAdHocProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testEmbeddedProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testEmbeddedProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testAsyncWIH/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testAsyncWIH</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testMultipleInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testMultipleInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/PR_check___Build_projects___testParallelPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testParallelPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testPersistence/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testPersistence</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testMultipleEmbeddedInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testMultipleEmbeddedInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testAdHocProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testAdHocProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testEmbeddedProcess/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testEmbeddedProcess</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testAsyncWIH/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testAsyncWIH</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3791/2/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/PR_check___Build_projects___testMultipleInstance/">PR check / Build projects / org.kie.kogito.it.PostgreSQLPersistenceIT.testMultipleInstance</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <500>.<br/>
</details>

**Pull request merged**
