### PR TITLE
[incubator-kie-issues-1522] Transition object to make extensible usertask transition restendpoint

### PR DESCRIPTION
**Pull request by elguardian**
Closes: https://github.com/apache/incubator-kie-issues/issues/1522

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3708 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/1/display/redirect

**Test results:**
- PASSED: 3366
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testMultiInstanceLoopBoundaryTimer/">org.jbpm.bpmn2.IntermediateEventTest.testMultiInstanceLoopBoundaryTimer</a></summary>
java.util.ConcurrentModificationException<br/>	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)<br/>	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)<br/>	at org.jbpm.workflow.instance.node.CompositeNodeInstance.getNodeInstances(CompositeNodeInstance.java:220)<br/>	at org.jbpm.workflow.instance.node.CompositeNodeInstance.getNodeInstances(CompositeNodeInstance.java:222)<br/>	at org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.getNodeInstances(WorkflowProcessInstanceImpl.java:217)<br/>	at org.kie.kogito.process.impl.AbstractProcessInstance.syncWorkItems(AbstractProcessInstance.java:584)<br/>	at org.kie.kogito.process.impl.AbstractProcessInstance.completeWorkItem(AbstractProcessInstance.java:556)<br/>	at org.jbpm.test.utils.ProcessTestHelper.completeWorkItem(ProcessTestHelper.java:114)<br/>	at org.jbpm.test.utils.ProcessTestHelper.completeWorkItem(ProcessTestHelper.java:79)<br/>	at org.jbpm.bpmn2.IntermediateEventTest.testMultiInstanceLoopBoundaryTimer(IntermediateEventTest.java:2032)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/1/testReport/org.kie.kogito.it/InfinispanPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.InfinispanPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <200> but was <500>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3708 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/3/display/redirect

**Test results:**
- PASSED: 2633
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3708 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/display/redirect

**Test results:**
- PASSED: 3368
- FAILED: 11

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.jbpm.bpmn2/StandaloneBPMNProcessTest/testEventBasedSplit2/">org.jbpm.bpmn2.StandaloneBPMNProcessTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/FilesystemPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.FilesystemPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/InfinispanOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.InfinispanOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/InfinispanPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.InfinispanPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/JDBCOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.JDBCOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/JDBCPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.JDBCPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/KafkaPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.KafkaPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/MongoDBOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.MongoDBOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/MongoDBPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.MongoDBPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/4/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.PostgreSQLPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3708 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/display/redirect

**Test results:**
- PASSED: 3366
- FAILED: 13

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/FilesystemPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.FilesystemPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/InfinispanOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.InfinispanOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/InfinispanPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.InfinispanPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/JDBCOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.JDBCOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/JDBCPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.JDBCPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/KafkaPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.KafkaPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/MongoDBOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.MongoDBOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/MongoDBPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.MongoDBPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/PostgreSQLOptimisticLockingIT/testStartApprovalAuthorized/">org.kie.kogito.it.PostgreSQLOptimisticLockingIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/7/testReport/org.kie.kogito.it/PostgreSQLPersistenceIT/testStartApprovalAuthorized/">org.kie.kogito.it.PostgreSQLPersistenceIT.testStartApprovalAuthorized</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <404>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#9` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3708 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/9/display/redirect

**Test results:**
- PASSED: 3377
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/9/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/9/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3708/9/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Review by martinweiler — APPROVED** [review]
LGTM @elguardian

**Pull request merged**
