### PR TITLE
[Fix_#3546] NodeInstanceFactoryProvided not included in native build

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3546. This is an issue in native build consequence of the refactor done by https://github.com/apache/incubator-kie-kogito-runtimes/pull/3482
I think including the service loader classes should be enough for native compiler to realize it should include all node classes, but @domhanak please let us know if the issue is fixed by this change

### CODE REVIEW

**Comment by fjtirado** [comment]
@domhanak Stil not working. It seems more stuff needs to be added. Working on that

**Comment by fjtirado** [comment]
Working now

**Review by ricardozanini — APPROVED** [review]

**Comment by elguardian** [comment]
@fjtirado this was fixed in documentation as for service loader it is required 

[uarkus.native.auto-service-loader-registration](https://es.quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus-native-auto-service-loader-registration)

This fixes this classloaders and futures ones. propably it is better solution to add this into an application.properties

**Comment by fjtirado** [comment]
> @fjtirado this was fixed in documentation as for service loader it is required
> 
> [uarkus.native.auto-service-loader-registration](https://es.quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus-native-auto-service-loader-registration)
> 
> This fixes this classloaders and futures ones. propably it is better solution to add this into an application.properties

Ill try and let you know (Im not sure if setting that property in the quarkus extension automatically scan the META-INF of all dependencies, in which case is indeed a better solution or it just scans the extension one, in which case it wont work)

**Comment by fjtirado** [comment]
Updated to use quarkus property rather than explicitly naming the service loader involved, thanks @elguardian

**Review by elguardian — APPROVED** [review]

**Pull request merged**
