### PR TITLE
Fix #3363

### LINKED ISSUE #3363: Event catching error for intermediate event in spring boot
### Describe the bug

Ref: https://blog.kie.org/2021/09/kogito-process-eventing-add-ons.html#comment-357

Regarding : kogito-process-eventing-add-ons
Issue on build tool : spring boot
issue: There is an issue in SpringBoot receiver class, which only listen for topics on default channel and ignore any other one.

For catching intermediate event in workflow with spring boot, i had provided below properties

kogito.addon.cloudevents.kafka.kogito_incoming_stream=start
kogito.addon.cloudevents.kafka.kogito_incoming_stream.intermediate=intermediate
kogito.addon.cloudevents.kafka.kogito_outgoing_stream=end

now after starting the workflow with “start” topic message, when i send a message to “intermediate” topic with the process instance id and type=”intermediate”, the workflow doesn’t recognise it.

However if I send the same message to “start” topic with process inst id and type=”intermediate” then the message gets caught and the workflow continues.

So only incoming and outgoing properties are recognised not the node specific(intermediate).

### Expected behavior

For :
kogito.addon.cloudevents.kafka.kogito_incoming_stream=start
kogito.addon.cloudevents.kafka.kogito_incoming_stream.intermediate=intermediate

Event sent to "intermediate" topic with process instance id should be caught by workflow and workflow should progress.

### Actual behavior

Only while sending event to "start" topic with "type": "intermediate" and process inst id works.

Events sent to "intermediate" topic are not recognised by workflow.

### How to Reproduce?

1. add a bpmn2 file with start, end and intermediate message event.
2. send event to start message and then to intermediate event node.
3. event to intermediate gets ignored.

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3363
Merge with https://github.com/apache/incubator-kie-kogito-examples/pull/1859

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3368 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/display/redirect

**Test results:**
- PASSED: 3336
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/maven.invoker.it/cloudevents-spring-boot-addon-it-invoked/cloudevents_spring_boot_addon_it_invoked/">maven.invoker.it.cloudevents-spring-boot-addon-it-invoked.cloudevents-spring-boot-addon-it-invoked</a></summary>
The build exited with code 1. See /home/jenkins/jenkins-agent/workspace/_jobs_kogito-runtimes-pr_PR-3368/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/springboot/addons/messaging/integration-tests/target/it/cloudevents-spring-boot-addon-it-invoked/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/org.kie.kogito.integrationtests/SpringBootKogitoExtensionInitializerTest/testKogitoExtension/">org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest.testKogitoExtension</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@62794582 testClass = org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7c24b813, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@58d75e99, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2805d709, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@27f981c6, org.springframework.boot.test.context.SpringBootTestAnnotation@18ad5138], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/org.kie.kogito.integrationtests/SpringBootTopicsInformationResourceTest/test/">org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest.test</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@dd737ea testClass = org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7c24b813, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@58d75e99, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2805d709, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@27f981c6, org.springframework.boot.test.context.SpringBootTestAnnotation@18ad5138], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3368 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/display/redirect

**Test results:**
- PASSED: 3336
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/maven.invoker.it/cloudevents-spring-boot-addon-it-invoked/cloudevents_spring_boot_addon_it_invoked/">maven.invoker.it.cloudevents-spring-boot-addon-it-invoked.cloudevents-spring-boot-addon-it-invoked</a></summary>
The build exited with code 1. See /home/jenkins/jenkins-agent/workspace/_jobs_kogito-runtimes-pr_PR-3368/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/springboot/addons/messaging/integration-tests/target/it/cloudevents-spring-boot-addon-it-invoked/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/org.kie.kogito.integrationtests/SpringBootKogitoExtensionInitializerTest/testKogitoExtension/">org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest.testKogitoExtension</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@43b4ec0c testClass = org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/3/testReport/org.kie.kogito.integrationtests/SpringBootTopicsInformationResourceTest/test/">org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest.test</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@61ab6521 testClass = org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>

**Review by nmirasch — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3368 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/display/redirect

**Test results:**
- PASSED: 3336
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/maven.invoker.it/cloudevents-spring-boot-addon-it-invoked/cloudevents_spring_boot_addon_it_invoked/">maven.invoker.it.cloudevents-spring-boot-addon-it-invoked.cloudevents-spring-boot-addon-it-invoked</a></summary>
The build exited with code 1. See /home/jenkins/jenkins-agent/workspace/_jobs_kogito-runtimes-pr_PR-3368/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/springboot/addons/messaging/integration-tests/target/it/cloudevents-spring-boot-addon-it-invoked/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/org.kie.kogito.integrationtests/SpringBootKogitoExtensionInitializerTest/testKogitoExtension/">org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest.testKogitoExtension</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@3a4cb483 testClass = org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/org.kie.kogito.integrationtests/SpringBootTopicsInformationResourceTest/test/">org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest.test</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@627acb38 testClass = org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3368 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/display/redirect

**Test results:**
- PASSED: 3336
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/maven.invoker.it/cloudevents-spring-boot-addon-it-invoked/cloudevents_spring_boot_addon_it_invoked/">maven.invoker.it.cloudevents-spring-boot-addon-it-invoked.cloudevents-spring-boot-addon-it-invoked</a></summary>
The build exited with code 1. See /home/jenkins/workspace/_jobs_kogito-runtimes-pr_PR-3368/kogito-pipelines/bc/apache_incubator-kie-kogito-runtimes/springboot/addons/messaging/integration-tests/target/it/cloudevents-spring-boot-addon-it-invoked/build.log for details.
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/org.kie.kogito.integrationtests/SpringBootKogitoExtensionInitializerTest/testKogitoExtension/">org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest.testKogitoExtension</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@40c0437f testClass = org.kie.kogito.integrationtests.SpringBootKogitoExtensionInitializerTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/mcimbalek/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3368/4/testReport/org.kie.kogito.integrationtests/SpringBootTopicsInformationResourceTest/test/">org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest.test</a></summary>
Failed to load ApplicationContext for [WebMergedContextConfiguration@389a1e34 testClass = org.kie.kogito.integrationtests.SpringBootTopicsInformationResourceTest, locations = [], classes = [org.kie.kogito.app.KogitoSpringbootApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true", "server.port=0"], contextCustomizers = [org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7bd4937b, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@741a8937, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ea41516, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@1151e434, org.springframework.boot.test.context.SpringBootTestAnnotation@83357af6], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
</details>

**Pull request merged**
