### PR TITLE
[KOGITO-9810] Supporting nested properties

### PR DESCRIPTION
**Pull request by fjtirado**
This adds support for nested properties when using $SECRET

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins rerun tests

**Comment by fjtirado** [comment]
jenkins run this

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins run kogito-runtimes tests

**Review by ricardozanini — APPROVED** [review]
Elegant.

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3229 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/7/display/redirect

**Test results:**
- PASSED: 3386
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/7/testReport/org.kie.kogito.addon.quarkus.messaging.common/QuarkusEventThreadPoolTest/testQuarkusEventThreadPoolMultiThreadLongQueueTest/">org.kie.kogito.addon.quarkus.messaging.common.QuarkusEventThreadPoolTest.testQuarkusEventThreadPoolMultiThreadLongQueueTest</a></summary>
expected: not equal but was: <0>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/7/testReport/org.kie.kogito.quarkus.workflows/ExpressionRestFromImageIT/testExpressionRest/">org.kie.kogito.quarkus.workflows.ExpressionRestFromImageIT.testExpressionRest</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <400>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3229 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/8/display/redirect

**Test results:**
- PASSED: 3388
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/8/testReport/org.kie.kogito.quarkus.workflows/ExpressionRestFromImageIT/testExpressionRest/">org.kie.kogito.quarkus.workflows.ExpressionRestFromImageIT.testExpressionRest</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <400>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3229 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/2/display/redirect

**Test results:**
- PASSED: 2429
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/2/testReport/org.kie.kogito.quarkus.workflows/ExpressionRestFromImageIT/testExpressionRest/">org.kie.kogito.quarkus.workflows.ExpressionRestFromImageIT.testExpressionRest</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <400>.<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3229 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/3/display/redirect

**Test results:**
- PASSED: 3388
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/test/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/3/testReport/org.kie.kogito.infinispan.health/InfinispanHealthCheckIT/testCall/">org.kie.kogito.infinispan.health.InfinispanHealthCheckIT.testCall</a></summary>
java.lang.reflect.InvocationTargetException
</details>

**Comment by kie-ci3** [comment]
**PR job** `#10` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3229 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/10/display/redirect

**Test results:**
- PASSED: 3387
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/10/testReport/org.kie.kogito.addon.quarkus.messaging.common/QuarkusEventThreadPoolTest/testQuarkusEventThreadPoolMultiThreadLongQueueTest/">org.kie.kogito.addon.quarkus.messaging.common.QuarkusEventThreadPoolTest.testQuarkusEventThreadPoolMultiThreadLongQueueTest</a></summary>
expected: not equal but was: <0>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3229/10/testReport/org.kie.kogito.quarkus.workflows/AsyncAPIIT/testConsumer/">org.kie.kogito.quarkus.workflows.AsyncAPIIT.testConsumer</a></summary>
Unexpected error in InitProducerIdResponse; The broker is not available.
</details>

**Pull request merged**
