### PR TITLE
[kie-issues#1610] Remove WorkItemDefinition mechanism

### PR DESCRIPTION
**Pull request by josedee**
Closes https://github.com/apache/incubator-kie-issues/issues/1610

Remove WorkItemDefinition mechanism from the Workflow engine (.wid) files support on the BPMN Editor / engine.

### CODE REVIEW

**Review by yesamer — COMMENTED** [review]
HI @josedee, thank you for your PR.
I found some references of *.wid files in 
- `.gitignore` files
- pom.xml related to springboot integration tests

To find them, you need to search `*.wid` key in the repo.
I guess we should remove them too, is that right @elguardian ?

**Comment by yesamer** [comment]
@josedee  Thank you for applying the changes!

@josedee @elguardian @pefernan @martinweiler  I noticed we have a lot of wid files in the repo (eg `apache/incubator-kie-kogito-runtimes/jbpm/jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repositorysingledir/repowid.wid`), should we remove them all?

Screenshot 2024-11-14 at 18 21 56

**Review by yesamer — APPROVED** [review]
@josedee Thank you!

**Review by pefernan — APPROVED** [review]

**Comment by porcelli** [comment]
follow up issue: we need a mechanism in place to replace WID files https://github.com/apache/incubator-kie-issues/issues/1676

**Pull request merged**
