### PR TITLE
[Fix #3415] Allow constant values in user task assignments

### LINKED ISSUE #3415: Cannot assing a constant value to a user task variable
### Describe the bug

Adding a new variable and assigning it a constant value in quarkus-usertask-example like in the following snapshot
image
causes a codegen exception

### Expected behavior

The variable is added to the task

### Actual behavior

An IllegalArgumentException is thrown

### Additional information

See https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/BPMN.20Task.20Variable.20expressions/near/423366829 

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3415

The older regular expression check does not longer makes sense, It prevents variables in user task model generated classes to be assigned to constant values.

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3416 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/1/display/redirect

**Test results:**
- PASSED: 2262
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/1/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[25]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[25]</a></summary>
Value <#{person.name}> is not valid for datatype: org.jbpm.process.core.datatype.impl.type.ObjectDataType@4fffe3d1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/1/testReport/org.kie.kogito.codegen.tests/UserTaskIT/testUserTaskWithIOexpressionProcess/">org.kie.kogito.codegen.tests.UserTaskIT.testUserTaskWithIOexpressionProcess</a></summary>
Value <#{person.name}> is not valid for datatype: org.jbpm.process.core.datatype.impl.type.ObjectDataType@4fffe3d1
</details>

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3416 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/3/display/redirect

**Test results:**
- PASSED: 2626
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/3/testReport/org.kie.kogito.codegen.process/ProcessGenerationIT/testProcessGeneration(String)[25]/">org.kie.kogito.codegen.process.ProcessGenerationIT.testProcessGeneration(String)[25]</a></summary>
Value <#{person.name}> is not valid for datatype: org.jbpm.process.core.datatype.impl.type.ObjectDataType@4fffe3d1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3416/3/testReport/org.kie.kogito.codegen.tests/UserTaskIT/testUserTaskWithIOexpressionProcess/">org.kie.kogito.codegen.tests.UserTaskIT.testUserTaskWithIOexpressionProcess</a></summary>
Value <#{person.name}> is not valid for datatype: org.jbpm.process.core.datatype.impl.type.ObjectDataType@4fffe3d1
</details>

**Review by elguardian — CHANGES_REQUESTED** [review]
expressions are something we cannot removed as they are used. You can add constants if you like in other way. not very sure what is the feedback that triggers removing this feature.
I am not against to support constants as such but you might need to find another way.

**Comment by fjtirado** [comment]
@elguardian We are not removing anything, we are allowing setting constants but adding the variable in the case the value is not an expression

**Review by elguardian — APPROVED** [review]

**Review by gmunozfe — COMMENTED** [review]
Looks good to me, just add a test at `ActivityGenerationModelTest#testUserTaskProcessWithTaskModels` in jbpm-bpmn2, modifying the `BPMN2-UserTask.bpmn2 ` to check that the constant is treated correctly.

**Review by gmunozfe — APPROVED** [review]
Great, thanks for adding the test, nice! @fjtirado

**Pull request merged**
