### PR TITLE
[incubator-kie-issues-1305] Flow v7 Migration port

### PR DESCRIPTION
**Pull request by elguardian**
Closes: https://github.com/apache/incubator-kie-issues/issues/1305

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3550 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3550/4/display/redirect

**Test results:**
- PASSED: 3261
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3550/4/testReport/org.jbpm.bpmn2.structureref/StructureRefTest/testNotExistingBooleanStructureRefOnWIComplete/">org.jbpm.bpmn2.structureref.StructureRefTest.testNotExistingBooleanStructureRefOnWIComplete</a></summary>
Data output 'not existing' is not defined in process 'IntegerStructureRef' for task 'User Task'
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3550 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3550/5/display/redirect

**Test results:**
- PASSED: 3264
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3550/5/testReport/org.jbpm.bpmn2.structureref/StructureRefTest/testNotExistingBooleanStructureRefOnWIComplete/">org.jbpm.bpmn2.structureref.StructureRefTest.testNotExistingBooleanStructureRefOnWIComplete</a></summary>
Data output 'not existing' is not defined in process 'IntegerStructureRef' for task 'User Task'
</details>

**Review by martinweiler — CHANGES_REQUESTED** [review]
Failing test `StructureRefTest.testNotExistingBooleanStructureRefOnWIComplete`

**Review by martinweiler — APPROVED** [review]

**Review by pefernan — APPROVED** [review]
+1 when green

**Pull request merged**
