### PR TITLE
Downgrade DefaultInstanceEventBatch trace level to debug

### PR DESCRIPTION
**Pull request by gmunozfe**
Downgrade the trace level of this recurrent trace because it's very noisy 

Many thanks for submitting your Pull Request :heart:!

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3698 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3698/1/display/redirect

**Test results:**
- PASSED: 3331
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3698/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testTimerBoundaryEventInterrupting/">org.jbpm.bpmn2.IntermediateEventTest.testTimerBoundaryEventInterrupting</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3698/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerDuration/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerDuration</a></summary>
<br/>expected: 2<br/> but was: 1
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3698/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventBasedSplit2/">org.jbpm.bpmn2.IntermediateEventTest.testEventBasedSplit2</a></summary>
<br/>expected: 2<br/> but was: 1
</details>

**Review by elguardian — APPROVED** [review]
LGTM. Thanks for fixing this.

**Review by domhanak — APPROVED** [review]

**Comment by elguardian** [comment]
@gmunozfe plz rebase.

**Comment by fjtirado** [comment]
@gmunozfe Seems that @elguardian has already downgrade it to trace (And I feel thats preferable to even debug), therefore closing this PR.

**Pull request closed without merging**
