### PR TITLE
[NO ISSUE] Update maven-plugin-plugin version to fix Java 17 compilation

### PR DESCRIPTION
**Pull request by baldimir**
The version of maven-plugin-plugin was not compatible with Java 17. After the upgrade, the compilaton works.

### CODE REVIEW

**Review by mariofusco — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3340 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3340/1/display/redirect

**Test results:**
- PASSED: 2428
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3340/1/testReport/org.kie.kogito.quarkus.workflows/ExpressionRestFromImageIT/testExpressionRest/">org.kie.kogito.quarkus.workflows.ExpressionRestFromImageIT.testExpressionRest</a></summary>
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
</details>

**Comment by baldimir** [comment]
I disabled another test - here is an issue for it https://github.com/apache/incubator-kie-issues/issues/788

**Comment by fjtirado** [comment]
@baldimir What was not compiling with previous maven plugin version?

**Review by pefernan — APPROVED** [review]

**Comment by pefernan** [comment]
Not sure if I'd disable the test on this PR, but approving to fix the build

**Comment by baldimir** [comment]
@fjtirado the build of kogito-maven-plugin failed on unsupported class format.

**Comment by fjtirado** [comment]
@baldimir Lets disable the test with a different PR

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3340 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3340/2/display/redirect

**Test results:**
- PASSED: 3330
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3340/2/testReport/org.kie.kogito.quarkus.workflows/ExpressionRestFromImageIT/testExpressionRest/">org.kie.kogito.quarkus.workflows.ExpressionRestFromImageIT.testExpressionRest</a></summary>
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
</details>

**Pull request merged**
