### PR TITLE
[incubator-kie-issues-1131] test migration from V7 to code generation-8

### PR DESCRIPTION
**Pull request by Abhitocode**
In addition to previous changes associated,
Migrated tests within  CompensationTest.Java

The test can be identified by referring to CompensationTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/CompensationTest.java

Closes https://github.com/apache/incubator-kie-issues/issues/1131.

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3593 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3593/1/display/redirect

**Test results:**
- PASSED: 3279
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3593/1/testReport/org.jbpm.bpmn2/CompensationTest/compensationInSubSubProcesses/">org.jbpm.bpmn2.CompensationTest.compensationInSubSubProcesses</a></summary>
Process could not be validated ![Process 'Default Process' [InSubSubProcess]: Node 'Boundary Compensate 3' [_X-1] Event has no outgoing connection, Process 'Default Process' [InSubSubProcess]: Node 'Compensate Handler 3' [_X-2] Action has no incoming connection., Process 'Default Process' [InSubSubProcess]: Node 'Boundary Compensate 2' [_Y-1] Event has no outgoing connection, Process 'Default Process' [InSubSubProcess]: Node 'Compensate Handler 2' [_Y-2] Action has no incoming connection., Process 'Default Process' [InSubSubProcess]: Node 'Compensate Handler 3' [_X-2] Has no connection to the start node., Process 'Default Process' [InSubSubProcess]: Node 'Compensate Handler 2' [_Y-2] Has no connection to the start node.]
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3593/1/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycle3/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycle3</a></summary>
<br/>expected: 3<br/> but was: 2
</details>

**Comment by elguardian** [comment]
@Abhitocode try to debug RuleFlowProcessValidator and check whether the error comes from.

**Review by elguardian — APPROVED** [review]
LGTM

**Review by martinweiler — APPROVED** [review]

**Comment by elguardian** [comment]
@Abhitocode fix CI plz.

**Pull request merged**
