### PR TITLE
[incubator-kie-issues#847] Include generated-resources to quarkus artifact

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/847
Requires  https://github.com/apache/incubator-kie-drools/pull/5765
Required by https://github.com/apache/incubator-kie-kogito-examples/pull/1889

This PR add the "target/generated-resources" to the collection of scanned directory for resource discovery.
This is needed to allow inclusion of models from external artifacts.
Original discussion may be found [here](https://community.ibm.com/community/user/automation/discussion/quarkus-kogito-extension-maven-project-with-generated-dmn-resources-from-another-maven-dependency#bmb1e1ec67-dde7-4be3-aa07-018d35869f98)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Review by baldimir — APPROVED** [review]

**Comment by gitgabrio** [comment]
Kogito -apps failure unrelated
continuous-integration failure unrelated -> `[2024-03-06T10:51:01.539Z] Cannot contact jenkins-shared-ubuntu-2: java.lang.InterruptedException`

**Comment by gitgabrio** [comment]
Kogito Runtimes failure unrelated
`2024-03-07T13:53:17.9561374Z ℹ️ - JUnit Test Report - 3284 tests run, 3225 passed, 52 skipped, 7 failed.
2024-03-07T13:53:17.9563156Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/rules/PublishEventBusinessRuleIT.java | expected: "2"
2024-03-07T13:53:17.9565514Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java | No value present
2024-03-07T13:53:17.9567444Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java | No value present
2024-03-07T13:53:17.9569362Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java | expected: 5
2024-03-07T13:53:17.9571516Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java | expected: "2"
2024-03-07T13:53:17.9573462Z    🧪 - apache_incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java | No value present
2024-03-07T13:53:17.9576283Z    🧪 - apache_incubator-kie-kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/WorkflowEventIT.java | org.opentest4j.AssertionFailedError: expected: <ProcessInstanceStateEvent> but was: <ProcessInstanceStateDataEvent>`

**Review by porcelli — CHANGES_REQUESTED** [review]
would be possible to introduce some test for the changes? so we'd be able to make sure we won't have a regression in the future?

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3427 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/display/redirect

**Test results:**
- PASSED: 3205
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.rules/PublishEventBusinessRuleIT/testBusinessRuleProcessStartToEnd/">org.kie.kogito.codegen.rules.PublishEventBusinessRuleIT.testBusinessRuleProcessStartToEnd</a></summary>
<br/>expected: "2"<br/> but was: "0"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcessAbort/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcessAbort</a></summary>
No value present
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcessWithSecurityRoles/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcessWithSecurityRoles</a></summary>
No value present
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testServiceTaskProcessWithError/">org.kie.kogito.codegen.tests.PublishEventIT.testServiceTaskProcessWithError</a></summary>
<br/>expected: 5<br/> but was: 0
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testExclusiveGatewayStartToEnd/">org.kie.kogito.codegen.tests.PublishEventIT.testExclusiveGatewayStartToEnd</a></summary>
<br/>expected: "2"<br/> but was: "0"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcess/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcess</a></summary>
No value present
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/6/testReport/org.kie.kogito.quarkus.workflows/WorkflowEventIT/testWorkflowEvents/">org.kie.kogito.quarkus.workflows.WorkflowEventIT.testWorkflowEvents</a></summary>
org.opentest4j.AssertionFailedError: expected: <ProcessInstanceStateEvent> but was: <ProcessInstanceStateDataEvent>
</details>

**Comment by gitgabrio** [comment]
> would be possible to introduce some test for the changes? so we'd be able to make sure we won't have a regression in the future?

Just done
Note:
1. I had to slightly refactor my modification for easy of testing
2. that module has never been tested at all, so I made a very single, focalized test only for my modification

**Comment by gitgabrio** [comment]
Kogito-apps failure unrelated
```
##[group]🚀 Publish results
2024-03-08T12:28:42.4520450Z ℹ️ - JUnit Test Report - 1693 tests run, 1673 passed, 10 skipped, 10 failed.
2024-03-08T12:28:42.4524914Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/infinispan/ProcessDataIndexInfinispanHttpIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4530268Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/infinispan/ProcessDataIndexInfinispanKafkaIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4534119Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/inmemory/ProcessDataIndexInMemoryIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4537590Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/mongodb/ProcessDataIndexMongoDBHttpIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4541068Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/mongodb/ProcessDataIndexMongoDBKafkaIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4544585Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/postgresql/ProcessDataIndexPostgreSqlHttpIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4548131Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/src/test/java/org/kie/kogito/index/postgresql/ProcessDataIndexPostgreSqlKafkaIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4551903Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-springboot/src/test/java/org/kie/kogito/index/ProcessDataIndexInfinispanIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4555406Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-springboot/src/test/java/org/kie/kogito/index/ProcessDataIndexMongoDBIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4558932Z    🧪 - apache_incubator-kie-kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-springboot/src/test/java/org/kie/kogito/index/ProcessDataIndexPostgreSqlIT.java | Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
2024-03-08T12:28:42.4598892Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4603175Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4606760Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.ProcessInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4610560Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4614217Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4617717Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.ProcessInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4621096Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.ProcessInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4624702Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4628335Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.Approvals[0].metadata.processInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4632159Z ##[error]Assertion condition defined as a org.kie.kogito.index.AbstractProcessDataIndexIT 1 expectation failed.
JSON path data.ProcessInstances[0].state doesn't match.
Expected: is "ACTIVE"
  Actual: PENDING
 within 30 seconds.
2024-03-08T12:28:42.4633481Z ##[endgroup]
```

**Comment by kie-ci3** [comment]
**PR job** `#7` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3427 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/display/redirect

**Test results:**
- PASSED: 2270
- FAILED: 8

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.jbpm.bpmn2/IntermediateEventTest/testEventSubprocessWithEmbeddedSignals/">org.jbpm.bpmn2.IntermediateEventTest.testEventSubprocessWithEmbeddedSignals</a></summary>
testEventSubprocessWithEmbeddedSignals() timed out after 3000 seconds
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.jbpm.bpmn2/StartEventTest/testTimerStartCycleLegacy/">org.jbpm.bpmn2.StartEventTest.testTimerStartCycleLegacy</a></summary>
testTimerStartCycleLegacy() timed out after 3000 seconds
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.rules/PublishEventBusinessRuleIT/testBusinessRuleProcessStartToEnd/">org.kie.kogito.codegen.rules.PublishEventBusinessRuleIT.testBusinessRuleProcessStartToEnd</a></summary>
<br/>expected: "2"<br/> but was: "0"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcessAbort/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcessAbort</a></summary>
No value present
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcessWithSecurityRoles/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcessWithSecurityRoles</a></summary>
No value present
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testServiceTaskProcessWithError/">org.kie.kogito.codegen.tests.PublishEventIT.testServiceTaskProcessWithError</a></summary>
<br/>expected: 5<br/> but was: 0
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testExclusiveGatewayStartToEnd/">org.kie.kogito.codegen.tests.PublishEventIT.testExclusiveGatewayStartToEnd</a></summary>
<br/>expected: "2"<br/> but was: "0"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3427/7/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcess/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcess</a></summary>
No value present
</details>

**Review by mariofusco — APPROVED** [review]

**Review by porcelli — APPROVED** [review]
I'd love to see if we could adjust some of the code to use NIO2 api and not manipulate strings to check file extensions. but can be done in different PR.

**Pull request merged**
